<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net6.0;net8.0;net9.0;netstandard2.0;netstandard2.1</TargetFrameworks>
        <Nullable>enable</Nullable>
        <LangVersion>10.0</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Coplt.Dropping.Analyzers\Coplt.Dropping.Analyzers.csproj" ReferenceOutputAssembly="false" PrivateAssets="all"/>
    </ItemGroup>

</Project>
